### ISSUE TITLE
Differentiate color for reserved HTML element names, custom elements

### ISSUE THREAD

**Issue by zvuc** [radium-v/Better-Less#11]
Please select any editor that you're experiencing this issue in.
- [v] Sublime Text 2/3

Please provide the name/repo of the color scheme package you're using:
- Tomorrow Night
---

First of all, thanks for taking the lead in effort to make a more up-to-date LESS syntax highlighter. The previous LESS highlighter has definitely been outdated and felt like it needed some work, I'm glad I'm not the only one that feels that way.

I tried out your plugin and noticed a few parts that needed some more work / fixing. I'll post separate issues for different parts.

![less-syntax-highlight-test](https://user-images.githubusercontent.com/2870726/30414630-7fe401b8-995f-11e7-94f2-154b4c50d1be.jpg)
I made a little test sheet to compare syntax highlighting by the previous [LESS](https://github.com/danro/LESS-sublime) (by danro) plugin and Better LESS.

## Reserved HTML element names
In current implementation, the reserved HTML element names (`span`,`header`,`article`, etc) appear in the same color as `.class` names, so it's a bit difficult to distinguish when they're used alongside IDs or class names like `span.text-label`.

## Custom elements
Also, custom element names should be separately colored too in my opinion. This is the part where the old LESS highlighter lacked the most (probably because custom elements are still fairly new to be used in production?) where it incorrectly highlighted the part of the name if it contained a reserved word (like in example `video-container`). It still did highlight it correctly when it didn't start with a reserved word and was `hyphen-delimited`, and a bit weird in that it highlighted Capital letter of a `camelCase` class name.

Better LESS on the other hand handles custom elements alright with exception of camelCase named elements somehow, but I think this is partly because currently Better LESS doesn't give special treatment (dictionary) for reserved HTML element names as I mentioned above. (Correct me if I'm wrong)

**Comment by radium-v** [comment]
Hi @zvuc,

Thank you so much for your help! Knowing there's someone out there who cares about this as much as me is exciting.

This feedback is invaluable. The test Less provided here exposes quite a few different bugs - I'll investigate and make some issues for the ones that you haven't already split out for me.

I'll leave a comment later this evening after I spend some time going through your feedback here.

**Comment by radium-v** [comment]
With regards to reserved HTML elements, they are being properly scoped in Better Less. The default schemes in Sublime Text (and most editors) don't properly differentiate punctuation, meta selector tokens, etc. I may contribute to some of the popular or built-in color schemes to accommodate these scopes, since some of them are missing while others are explicitly targeting `.css` or `.css.less` ([I'm](https://github.com/atom/atom-dark-syntax/blob/master/styles/syntax.less#L175) [looking](https://github.com/atom/atom-light-syntax/blob/master/styles/syntax.less#L148) [at](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax/css.less) [you](https://github.com/atom/solarized-dark-syntax/blob/master/styles/syntax/css.less), [Atom](https://github.com/atom/one-light-syntax/blob/master/styles/syntax/css.less)) which is the reason for #10.

The custom elements syntax regex is [based on this spec](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) which requires that the custom name have a dash in it. Better Less does differentiate between an `entity.name.tag` and an `entity.name.tag.custom` which matches Sublime's CSS3 scopes AFAICR. The differences in color choice need to come from the color scheme you're using.

This means that `container`, `wrapper`, and `videoContainer` are invalid as custom elements in CSS, but they're still valid `meta.selector`s.

I have fixes for `animation-name`, `::host`, `::host-context`, `::slotted`, and `::selection` coming soon. I'll include `/deep/` as a deprecated scope as well.
