### ISSUE TITLE
Add sublime-syntax format

### ISSUE THREAD

**Issue by radium-v** [radium-v/Better-Less#6]
Turns out ST3 can directly convert `tmLanguage` files to `sublime-syntax`. Are there advantages to using the new syntax over the old, and if so, would that split development into two separate builds?

**Comment by jrappen** [comment]
See sublimehq/Packages#115 for one major difference.

**Comment by radium-v** [comment]
It looks like @braver has a package [LessImproved](https://github.com/braver/LessImproved) which focuses on ST3 support. It would be cool to discuss differences between these packages, since we both started by modifying the `CSS.sublime-syntax` package.

**Comment by braver** [comment]
@radium-v actually, I mostly used the CSS package as a basis for the auto-complete suggestions. LessImproved is otherwise a mixture of danro's old Less package and work I did some time ago to improve Atom's Less package. I would prefer it if there was one really good package for Less, but danro's is basically dead and he hasn't responded to my pull request for ages. 

That said, I don't believe in a single code base outputting packages for multiple editors. VS Code seems to be quite faithful to Textmate's implementation, but Sublime (using sublime-syntax instead of tmLanguage) and Atom are completely different and much more powerful. Atom for one already has a pretty awesome Less package, which isn't surprising because it ties so strongly to the suggestions engine and Less is a core language for the editor itself. So I doubt you'll surpass it there, or get any significant traction. 

But if you want to contribute to my package, you're totally welcome.

**Comment by radium-v** [comment]
Hi @braver, thanks for the response.

Atom's Less package is based on the original [TextMate bundle](https://github.com/textmate/less.tmbundle) (which itself was forked from a [7-year old package](https://github.com/appden/less.tmbundle)). Atom's syntax format is pretty much the same as the tmLanguage, only it's json/cson encoded.

There are actually a lot of things that are broken in Atom's built-in Less package, like this example:

```css
@import url("style.css") screen and (min-width: 800px);
```

**Comment by braver** [comment]
Atom's less package being based on something stopped being true after yours truly basically rewrote the thing. But I'm sure there are things broken. If you want to fix them, the thing to do is make a pull request, not another package. Danro's package still gets about 30x the installs per day then LessImproved. Atom's package is pre-installed. You will not get traction and it just splinters the community. Also, the format may be similar, the implementation isn't.
I mean, not to rain on your parade or discourage you, but the best way forward usually isn't adding a new lowest common denominator package to what's already available.
